kor=int(input('Kor atmeroje:'))
print('Kor sugara:',kor//2)
print('pi ertek:3.14')
print('A kor kerulete:',2*kor//2*3.14,('cm'))
print('A kor terulete:',kor//2*kor//2*3.14,('cm2'))
print('Az/A',kor,'atmeroju kornek',2*kor//2*3.14,'cm a kerultete es',kor//2*kor//2*3.14,'cm2 a terulete')
