Penz=int(input('Mennyiseg?'))
Suti=int(input('Darab:'))
Fizeto=int(input('Mennyiseg?'))
Keksz=int(input('Drab:'))
Euro=int(input('Mennyiseg?'))
Piskota=int(input('Darab:'))
print('5eurosok szama:',Penz)
print('2eurosok szama:',Fizeto)
print('1eurosok szama:',Euro)
print('Ez osszesen',Suti*Penz+Keksz*Fizeto+Piskota*Euro)
