Szam1=int(input('Adja meg az elso szamot:'))
Szam2=int(input('Adja meg a masodik szamot'))
print('osztas eredmenye',Szam1//Szam2)
print('maradek',Szam1%Szam2)
print('osztas tizedes ertekre',Szam1/Szam2)
